# Generated by Django 6.0.5 on 2026-07-30 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_next', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationsession',
            name='is_first_question',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='conversationsession',
            name='request_type',
            field=models.CharField(choices=[('NEW_LOCATION', 'New Location'), ('FOLLOW_UP', 'Follow Up')], default='NEW_LOCATION', max_length=30),
        ),
        migrations.AlterField(
            model_name='analysisrecord',
            name='analysis_metrics',
            field=models.JSONField(help_text='Complete ML output including land-cover and LST expert-system analysis.'),
        ),
        migrations.AlterField(
            model_name='analysisrecord',
            name='model_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Versions of models, expert system, and LLM used.'),
        ),
    ]
