# Generated by Django 6.0.5 on 2026-08-04 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_next', '0002_conversationsession_is_first_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisrecord',
            name='analysis_metrics',
            field=models.JSONField(help_text='Complete climate analysis output including land-cover analysis and LST expert-system results.'),
        ),
        migrations.AlterField(
            model_name='analysisrecord',
            name='bbox',
            field=models.JSONField(help_text='Bounding box in the format [min_lon, min_lat, max_lon, max_lat].'),
        ),
        migrations.AlterField(
            model_name='analysisrecord',
            name='model_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Metadata describing the models, expert system, raster provider, and other analysis components.'),
        ),
        migrations.AlterField(
            model_name='conversationsession',
            name='analysis',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_session', to='core_next.analysisrecord'),
        ),
    ]
